# entrypoint for kicking off a unified build of the mathlibs
# sets `unifiedBuild` to true, which will prevent duplicate jobs
# logic needs to be added in individual mathlib pipelines for handling the `unifiedBuild` param

parameters:
- name: buildDependsOn
  type: object
- name: downstreamComponentMatrix
  type: object
  default:
    - rocRAND:
      name: rocRAND
      sparseCheckoutDir: projects/rocrand
    - rocPRIM:
      name: rocPRIM
      sparseCheckoutDir: projects/rocprim
    - hipBLAS-common:
      name: hipBLAS-common
      sparseCheckoutDir: projects/hipblas-common
    - composable_kernel:
      name: composable_kernel
      sparseCheckoutDir: projectscomposablekernel

jobs:
- ${{ each component in parameters.downstreamComponentMatrix }}:
  - template: /.azuredevops/components/${{ component.name }}.yml@pipelines_repo
    parameters:
      sparseCheckoutDir: ${{ component.sparseCheckoutDir }}
      buildDependsOn: ${{ component.buildDependsOn }}
      downstreamAggregateNames: ${{ parameters.downstreamAggregateNames }}+${{ parameters.componentName }}
      triggerDownstreamJobs: true
      unifiedBuild: true
