parameters:
- name: filename
  type: string

trigger: none
pr: none

jobs:
- job: springfield
  variables:
  - group: common
  - template: /.azuredevops/variables-global.yml
  pool: ${{ variables.GFX942_TEST_POOL }}
  workspace:
    clean: all
  steps:
    - checkout: none
    - task: Bash@3
      displayName: Download installer
      env:
        SPRINGFIELD_URL: $(SPRINGFIELD_URL)
      inputs:
        targetType: inline
        script: wget -nv "$SPRINGFIELD_URL/rocm/${{ parameters.filename }}" -O rocm-installer.run
    - task: Bash@3
      displayName: Install ROCm
      inputs:
        targetType: inline
        script: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt update
          mkdir -p $(Agent.BuildDirectory)
          chmod +x ./rocm-installer.run
          ./rocm-installer.run target='$(Agent.BuildDirectory)' deps=install rocm postrocm
    - task: Bash@3
      displayName: List ROCm files
      inputs:
        targetType: inline
        script: ls -la1R $(Agent.BuildDirectory)/rocm
    - task: Bash@3
      displayName: Setup & basic tests
      inputs:
        targetType: inline
        script: |
          export ROCM_PATH=$(Agent.BuildDirectory)/rocm
          export PATH=$PATH:$ROCM_PATH/bin
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ROCM_PATH/lib:$ROCM_PATH/llvm/lib
          export CXX=$ROCM_PATH/bin/amdclang++
          export CC=$ROCM_PATH/bin/amdclang
          rocminfo
          rocm_agent_enumerator
          rocm-smi
          amd-smi
