parameters:
- name: rocmFilename
  type: string
- name: wheelVersion
  type: string
- name: apexFilename
  type: string
- name: tritonFilename
  type: string
- name: torchFilename
  type: string
- name: visionFilename
  type: string

trigger: none
pr: none

jobs:
- job: springfield
  variables:
  - group: common
  - template: /.azuredevops/variables-global.yml
  pool: ${{ variables.GFX942_TEST_POOL }}
  workspace:
    clean: all
  steps:
    - checkout: none
    - task: Bash@3
      displayName: Setup
      inputs:
        targetType: inline
        script: |
          sudo DEBIAN_FRONTEND=noninteractive apt update
          sudo DEBIAN_FRONTEND=noninteractive apt install -y tzdata
          sudo DEBIAN_FRONTEND=noninteractive apt install -y python3.11 python3.11-venv

    - task: Bash@3
      displayName: Install Python wheels
      continueOnError: true
      env:
        SPRINGFIELD_URL: $(SPRINGFIELD_URL)
      inputs:
        targetType: inline
        script: |
          which python3.11 && python3.11 --version
          python3.11 -m venv $(Agent.BuildDirectory)/venv
          source $(Agent.BuildDirectory)/venv/bin/activate
          which python3 && python3 --version

          pip install $(SPRINGFIELD_URL)/wheels/${{ parameters.wheelVersion }}/rocroller/${{ parameters.apexFilename }} \
            $(SPRINGFIELD_URL)/wheels/${{ parameters.wheelVersion }}/rocroller/${{ parameters.tritonFilename }} \
            $(SPRINGFIELD_URL)/wheels/${{ parameters.wheelVersion }}/rocroller/${{ parameters.torchFilename }} \
            $(SPRINGFIELD_URL)/wheels/${{ parameters.wheelVersion }}/rocroller/${{ parameters.visionFilename }}

          pip install packaging wheel
          pip install git+https://github.com/rocm/flash-attention.git@ck_tile/fa3_fremont --no-build-isolation

    - script: python3 -c 'import torch'
      displayName: Test PyTorch import
      continueOnError: true
    - script: python3 -c 'import torch; print(torch.cuda.is_available())'
      displayName: Test PyTorch is_available()
      continueOnError: true

    - task: Bash@3
      displayName: Download installer
      env:
        SPRINGFIELD_URL: $(SPRINGFIELD_URL)
      inputs:
        targetType: inline
        script: wget -nv "$SPRINGFIELD_URL/rocm/${{ parameters.rocmFilename }}" -O rocm-installer.run
    - task: Bash@3
      displayName: Install ROCm
      inputs:
        targetType: inline
        script: chmod +x ./rocm-installer.run && ./rocm-installer.run target="$(Agent.BuildDirectory)" deps=install rocm postrocm
    - task: Bash@3
      displayName: List files
      inputs:
        targetType: inline
        script: ls -la1R $(Agent.BuildDirectory)
    - task: Bash@3
      displayName: Set env vars
      inputs:
        targetType: inline
        script: |
          export ROCM_PATH=$(Agent.BuildDirectory)/rocm
          export PATH=$PATH:$ROCM_PATH/bin
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ROCM_PATH/lib:$ROCM_PATH/llvm/lib
          export CXX=$ROCM_PATH/bin/amdclang++
          export CC=$ROCM_PATH/bin/amdclang

          echo "##vso[task.setvariable variable=ROCM_PATH]$ROCM_PATH"
          echo "##vso[task.prependpath]$ROCM_PATH/bin"
          echo "##vso[task.setvariable variable=LD_LIBRARY_PATH]$LD_LIBRARY_PATH"
          echo "##vso[task.setvariable variable=CXX]$CXX"
          echo "##vso[task.setvariable variable=CC]$CC"

    - script: rocminfo
      displayName: rocminfo
      continueOnError: true
    - script: rocm_agent_enumerator
      displayName: rocm_agent_enumerator
      continueOnError: true
    - script: rocm-smi
      displayName: rocm-smi
      continueOnError: true
    - script: amd-smi
      displayName: amd-smi
      continueOnError: true
    - script: amd-smi version
      displayName: amd-smi version
      continueOnError: true
    - script: amd-smi list
      displayName: amd-smi list
      continueOnError: true
    - script: amd-smi static
      displayName: amd-smi static
      continueOnError: true
    - script: amd-smi metric
      displayName: amd-smi metric
      continueOnError: true

    - task: Bash@3
      displayName: Build rocDecode
      continueOnError: true
      inputs:
        targetType: inline
        script: |
          mkdir -p $(Agent.BuildDirectory)/rocdecode
          cd $(Agent.BuildDirectory)/rocdecode
          cmake $ROCM_PATH/share/rocdecode/test
    - task: Bash@3
      displayName: Test rocDecode
      continueOnError: true
      inputs:
        targetType: inline
        script: ctest --output-on-failure --output-junit rocdecode_results.xml
        workingDirectory: $(Agent.BuildDirectory)/rocdecode
    - task: PublishTestResults@2
      displayName: Publish rocDecode
      continueOnError: true
      inputs:
        searchFolder: $(Agent.BuildDirectory)/rocdecode
        testResultsFormat: JUnit
        testResultsFiles: rocdecode_results.xml

    - task: Bash@3
      displayName: Build rocm-examples
      continueOnError: true
      inputs:
        targetType: inline
        script: |
          cd $(Agent.BuildDirectory)
          git clone https://github.com/ROCm/rocm-examples.git
          cd rocm-examples
          git checkout baae3b15bc300871b2d6830c4b170f2d7bb7c64b
          mkdir build && cd build
          cmake .. -DROCM_ROOT=$ROCM_PATH -DGPU_TARGETS=gfx942
          cmake --build . -- -j$(nproc)
    - task: Bash@3
      displayName: Test rocm-examples
      continueOnError: true
      inputs:
        targetType: inline
        script: ctest --output-on-failure --output-junit rocm-examples_results.xml
        workingDirectory: $(Agent.BuildDirectory)/rocm-examples/build
    - task: PublishTestResults@2
      displayName: Publish rocm-examples
      continueOnError: true
      inputs:
        searchFolder: $(Agent.BuildDirectory)/rocm-examples/build
        testResultsFormat: JUnit
        testResultsFiles: rocm-examples_results.xml
