// rust_vector_add/src/hip_utils.rs

/// This module provides raw FFI bindings to the HIP runtime API.
///
/// The bindings are generated by `bindgen` during the build process (see `build.rs`)
/// based on the `wrapper.h` header file. This module itself is generated by
/// `include!(concat!(env!("OUT_DIR"), "/bindings.rs"));` and contains `unsafe`
/// function definitions and type aliases corresponding to the HIP C API.
///
/// Users of this crate typically do not need to interact with `hip_bindings` directly,
/// as its contents are re-exported by `pub use hip_bindings::*;` into the `hip_utils`
/// module scope. For safety and convenience, use the `hip_call!` macro or other
/// safe wrappers provided in `hip_utils`.
#[allow(warnings)]
mod hip_bindings {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

/// Re-exports all FFI bindings from the `hip_bindings` module.
///
/// This makes all HIP runtime API functions (e.g., `hipMalloc`, `hipMemcpy`)
/// and types (e.g., `hipError_t`, `hipDeviceptr_t`) directly available under
/// the `hip_utils::` namespace.
///
/// For example, after `use rust_vector_add::hip_utils::*;`, you can call
/// `hipMalloc(...)` (though it's recommended to use the `hip_call!` macro).
pub use hip_bindings::*;

use anyhow::{anyhow, Result};
use std::ffi::CStr;
use std::fmt;

/// Represents an error returned from a HIP API call.
///
/// This struct is typically created by the `hip_call!` macro when a HIP
/// runtime function returns an error code other than `hipSuccess`.
#[derive(Debug)]
pub struct HipError {
    /// The raw HIP error code (`hipError_t`) returned by the HIP API function.
    pub code: hipError_t,
    /// A descriptive message for the error, obtained by calling `hipGetErrorString`
    /// with the `code`.
    pub message: String,
}

impl fmt::Display for HipError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "HIP Error (code {}): {}", self.code, self.message)
    }
}

impl std::error::Error for HipError {}

/// A macro to simplify calling HIP runtime API functions and checking their return codes.
///
/// It takes a HIP API call expression (which is typically `unsafe`), executes it,
/// and checks the returned `hipError_t` value.
///
/// If the result is not `hipSuccess` (the success code for HIP API calls),
/// it constructs and returns an `Err(anyhow::Error)` where the inner error
/// is a `HipError`. The `HipError` contains the original error code and a
/// human-readable message obtained using `hipGetErrorString`.
///
/// If the HIP API call is successful (returns `hipSuccess`), the macro
/// evaluates to `Ok(())`, allowing for easy chaining with the `?` operator.
///
/// # Safety
///
/// The expression passed to `hip_call!` is executed within an `unsafe` block
/// inside the macro. The caller is responsible for ensuring that the arguments
/// to the HIP call are valid (e.g., pointers point to valid memory, sizes are correct).
///
/// # Examples
///
/// ```ignore
/// use crate::hip_utils::{hip_call, hipMalloc, hipMemcpyKind}; // Assuming hip_utils is in scope
/// use std::ffi::c_void;
/// use std::ptr;
///
/// fn allocate_gpu_memory(size: usize) -> Result<*mut c_void, anyhow::Error> {
///     let mut device_ptr: *mut c_void = ptr::null_mut();
///     // The hipMalloc call is unsafe, but hip_call! handles the unsafe block and error checking.
///     hip_call!(hipMalloc(&mut device_ptr as *mut _ as *mut *mut c_void, size))?;
///     Ok(device_ptr)
/// }
/// ```
///
/// ```ignore
/// // Example of copying data (assuming d_a, h_a, and data_size are defined):
/// // hip_call!(hipMemcpy(
/// //     d_a,
/// //     h_a.as_ptr() as *const c_void,
/// //     data_size,
/// //     hipMemcpyKind::hipMemcpyHostToDevice
/// // ))?;
/// ```
#[macro_export]
macro_rules! hip_call {
    ($call:expr) => {{
        // The HIP API call itself is unsafe.
        let result = unsafe { $call };
        // Check if the call was successful.
        if result != $crate::hip_utils::hipSuccess {
            // If not, get the error string.
            let error_message = unsafe {
                let c_str = $crate::hip_utils::hipGetErrorString(result);
                if c_str.is_null() {
                    // Fallback message if hipGetErrorString returns null
                    "Unknown HIP error or hipGetErrorString failed".to_string()
                } else {
                    CStr::from_ptr(c_str).to_string_lossy().into_owned()
                }
            };
            // Construct and return our custom HipError wrapped in anyhow::Error.
            Err(anyhow!($crate::hip_utils::HipError {
                code: result,
                message: error_message,
            }))
        } else {
            // If successful, return Ok(()).
            Ok(())
        }
    }};
}

// No public functions were defined beyond the macro and re-exports in the original file.
// The example safe wrappers were commented out. If they were to be made public,
// they would also require /// doc comments. For example:

// /// Safely allocates memory on the current HIP device.
// ///
// /// Wraps the `hipMalloc` HIP runtime API function.
// ///
// /// # Parameters
// /// - `ptr`: A mutable pointer to a `hipDeviceptr_t` (effectively `*mut *mut c_void`)
// ///   which will be updated with the address of the allocated device memory.
// /// - `size`: The size of the memory to allocate in bytes.
// ///
// /// # Errors
// /// Returns `Err(HipError)` if `hipMalloc` fails.
// ///
// /// # Safety
// /// The caller must ensure that `ptr` is a valid pointer.
// pub fn safe_hip_malloc(ptr: *mut *mut ::std::os::raw::c_void, size: usize) -> Result<()> {
//     hip_call!(hipMalloc(ptr, size))
// }

// /// Safely frees memory on the current HIP device.
// ///
// /// Wraps the `hipFree` HIP runtime API function.
// ///
// /// # Parameters
// /// - `ptr`: A `hipDeviceptr_t` (effectively `*mut c_void`) pointing to the
// ///   device memory to be freed.
// ///
// /// # Errors
// /// Returns `Err(HipError)` if `hipFree` fails.
// ///
// /// # Safety
// /// The caller must ensure that `ptr` is a valid device pointer previously
// /// allocated by `hipMalloc` (or a similar HIP allocation function) and has not
// /// already been freed. Passing an invalid pointer can lead to undefined behavior.
// pub fn safe_hip_free(ptr: *mut ::std::os::raw::c_void) -> Result<()> {
//     hip_call!(hipFree(ptr))
// }

// /// Synchronizes the current HIP device.
// ///
// /// Waits until all preceding commands in all streams on the current device have completed.
// /// Wraps the `hipDeviceSynchronize` HIP runtime API function.
// ///
// /// # Errors
// /// Returns `Err(HipError)` if `hipDeviceSynchronize` fails.
// pub fn safe_hip_device_synchronize() -> Result<()> {
//     hip_call!(hipDeviceSynchronize())
// }
