// rust_vector_add/src/hip_utils.rs

// This line includes the bindings generated by bindgen from build.rs
// It expects bindings.rs to be in the OUT_DIR, which build.rs configures.
#[allow(warnings)]
mod hip_bindings {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

pub use hip_bindings::*; // Re-export all FFI bindings

use anyhow::{anyhow, Result};
use std::ffi::CStr;
use std::fmt;

// Custom Error type for HIP API calls
#[derive(Debug)]
pub struct HipError {
    pub code: hipError_t,
    pub message: String,
}

impl fmt::Display for HipError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "HIP Error ({}): {}", self.code, self.message)
    }
}

impl std::error::Error for HipError {}

// Macro to simplify calling HIP functions and checking their return codes.
#[macro_export]
macro_rules! hip_call {
    ($call:expr) => {{
        let result = unsafe { $call };
        if result != $crate::hip_utils::hipSuccess {
            let error_message = unsafe {
                let c_str = $crate::hip_utils::hipGetErrorString(result);
                if c_str.is_null() {
                    "Unknown HIP error".to_string()
                } else {
                    CStr::from_ptr(c_str).to_string_lossy().into_owned()
                }
            };
            Err(anyhow!($crate::hip_utils::HipError {
                code: result,
                message: error_message,
            }))
        } else {
            Ok(())
        }
    }};
}

// Example of a safe wrapper (optional, direct calls using hip_call! are also possible)
// pub fn safe_hip_malloc(ptr: *mut *mut ::std::os::raw::c_void, size: usize) -> Result<()> {
//     hip_call!(hipMalloc(ptr, size))
// }

// Add more safe wrappers here as needed, for example:
// pub fn safe_hip_free(ptr: *mut ::std::os::raw::c_void) -> Result<()> {
//     hip_call!(hipFree(ptr))
// }

// pub fn safe_hip_device_synchronize() -> Result<()> {
//     hip_call!(hipDeviceSynchronize())
// }
