// rust_vector_add/src/main.rs

#[macro_use] // To use hip_call! from hip_utils
extern crate log;

// Import the hip_utils module, which contains our FFI bindings, hip_call! macro, and HipError struct.
mod hip_utils;

use anyhow::{anyhow, Context, Result}; // For flexible error handling. `Context` adds more info to errors.
use hip_utils::*; // Imports hip_call, hipError_t, hipDeviceptr_t, hipModule_t, etc.
use std::ffi::{c_void, CString}; // For C-compatible strings and void pointers.
use std::mem; // For memory-related functions like size_of.
use std::path::Path; // For path manipulation and checking if the kernel file exists.
use std::ptr; // For using null_mut() for initial pointer values.
use std::time::Instant; // For basic timing of kernel execution and CPU computation.

// --- Constants ---

// KERNEL_PATH: File path to the compiled HIP kernel Code Object (.co).
// This file is generated by compiling `vectorAdd_kernel.hip` using `hipcc`.
// The application expects this file to be in the current working directory at runtime.
// Example compilation: `hipcc --genco vectorAdd_kernel.hip -o vectorAdd_kernel.co`
const KERNEL_PATH: &str = "./vectorAdd_kernel.co";

// VECTOR_SIZE: The number of elements in the vectors A, B, and C.
// This defines the total workload for the vector addition.
const VECTOR_SIZE: usize = 1024 * 1024; // 1 Mi-elements, chosen as an example size.

// THREADS_PER_BLOCK: The number of threads in each dimension of a HIP thread block.
// For this 1D kernel, it's the number of threads per block in the x-dimension.
// This value is often chosen based on GPU architecture to maximize occupancy, common values are 64, 128, 256.
const THREADS_PER_BLOCK: usize = 256;

fn main() -> Result<()> {
    // Initialize env_logger to enable logging based on RUST_LOG environment variable.
    env_logger::init();
    info!("Starting rust_vector_add application...");

    // --- Setup Problem Size ---
    // `n` is the number of elements in our vectors.
    let n = VECTOR_SIZE;
    // `data_size` is the total memory required for one vector of `n` f32 elements, in bytes.
    let data_size = n * mem::size_of::<f32>();

    // --- 1. Initialize Host Vectors ---
    // Create and fill host-side (CPU) vectors.
    // h_a and h_b are inputs, h_c_gpu will store the GPU result, h_c_cpu for CPU verification.
    info!("Initializing host vectors (A, B, C_cpu, C_gpu) of size {}", n);
    // h_a: Filled with 0.0, 1.0, 2.0, ...
    let mut h_a: Vec<f32> = (0..n).map(|i| i as f32).collect();
    // h_b: Filled with n, n-1, n-2, ...
    let mut h_b: Vec<f32> = (0..n).map(|i| (n - i) as f32).collect();
    // h_c_gpu: Initialized to zeros, will be filled with results from the GPU.
    let mut h_c_gpu: Vec<f32> = vec![0.0; n];
    // h_c_cpu: Initialized to zeros, will be filled with results computed by the CPU for verification.
    let mut h_c_cpu: Vec<f32> = vec![0.0; n];

    // --- 2. Allocate Device Memory ---
    // Allocate memory on the GPU for vectors d_a, d_b, and d_c.
    // `hipDeviceptr_t` is a raw pointer type for device memory, effectively `*mut c_void`.
    info!("Allocating device memory (d_A, d_B, d_C)");
    let mut d_a: hipDeviceptr_t = ptr::null_mut(); // Device pointer for vector A
    let mut d_b: hipDeviceptr_t = ptr::null_mut(); // Device pointer for vector B
    let mut d_c: hipDeviceptr_t = ptr::null_mut(); // Device pointer for result vector C (computed by GPU)

    // Use `scopeguard::guard` to ensure `hipFree` is called for each allocated device pointer,
    // even if the function returns early due to an error (similar to RAII or defer).
    // This helps prevent GPU memory leaks.
    // The `hip_call!` macro (from hip_utils.rs) wraps the unsafe `hipFree` call and converts errors.
    // `.expect` is used here as failure during cleanup is critical and indicates a severe issue.
    let mut _d_a_guard = scopeguard::guard(d_a, |ptr| {
        if !ptr.is_null() {
            debug!("Freeing d_A (device memory for vector A)");
            hip_call!(hipFree(ptr)).expect("Failed to free d_A during scope guard cleanup");
        }
    });
    let mut _d_b_guard = scopeguard::guard(d_b, |ptr| {
        if !ptr.is_null() {
            debug!("Freeing d_B (device memory for vector B)");
            hip_call!(hipFree(ptr)).expect("Failed to free d_B during scope guard cleanup");
        }
    });
    let mut _d_c_guard = scopeguard::guard(d_c, |ptr| {
        if !ptr.is_null() {
            debug!("Freeing d_C (device memory for result vector C)");
            hip_call!(hipFree(ptr)).expect("Failed to free d_C during scope guard cleanup");
        }
    });
    
    // `hipMalloc` allocates memory on the GPU.
    // It takes a pointer to a device pointer (`*mut hipDeviceptr_t`) and the size in bytes.
    // The `hip_call!` macro handles the `unsafe` call and error checking.
    // `anyhow::Context` provides additional context if an error occurs.
    hip_call!(hipMalloc(&mut d_a as *mut _ as *mut *mut c_void, data_size))
        .context("Failed to allocate device memory for vector A using hipMalloc")?;
    *_d_a_guard = d_a; // Update the guard with the actual allocated pointer.

    hip_call!(hipMalloc(&mut d_b as *mut _ as *mut *mut c_void, data_size))
        .context("Failed to allocate device memory for vector B using hipMalloc")?;
    *_d_b_guard = d_b; // Update guard

    hip_call!(hipMalloc(&mut d_c as *mut _ as *mut *mut c_void, data_size))
        .context("Failed to allocate device memory for result vector C using hipMalloc")?;
    *_d_c_guard = d_c; // Update guard

    // --- 3. Copy Data from Host to Device (H2D) ---
    // Transfer input data (h_a, h_b) from CPU (host) memory to GPU (device) memory.
    info!("Copying data from host to device (H2D)");
    // `hipMemcpy` is used for memory transfers.
    // Parameters: destination (device pointer), source (host pointer), size, kind of transfer.
    // `hipMemcpyKind::hipMemcpyHostToDevice` specifies a host-to-device transfer.
    hip_call!(hipMemcpy(
        d_a, // Destination: device memory for A
        h_a.as_ptr() as *const c_void, // Source: host memory for A (cast to *const c_void)
        data_size, // Size of data to copy
        hipMemcpyKind::hipMemcpyHostToDevice // Direction of copy
    ))
    .context("Failed HostToDevice hipMemcpy for vector A")?;

    hip_call!(hipMemcpy(
        d_b, // Destination: device memory for B
        h_b.as_ptr() as *const c_void, // Source: host memory for B
        data_size,
        hipMemcpyKind::hipMemcpyHostToDevice
    ))
    .context("Failed HostToDevice hipMemcpy for vector B")?;

    // --- 4. Load HIP Kernel Module ---
    // Load the pre-compiled GPU kernel from the .co file into a HIP module.
    info!("Loading HIP kernel module from: {}", KERNEL_PATH);
    // First, check if the kernel file actually exists at the specified path.
    // This provides a more user-friendly error than letting `fs::read` or `hipModuleLoadData` fail directly.
    if !Path::new(KERNEL_PATH).exists() {
        return Err(anyhow!("Kernel file not found: {}. Please compile vectorAdd_kernel.hip to .co using hipcc (e.g., hipcc --genco vectorAdd_kernel.hip -o vectorAdd_kernel.co).", KERNEL_PATH));
    }
    let mut module: hipModule_t = ptr::null_mut(); // Handle for the loaded HIP module.
    // `hipModuleLoadData` loads a compiled kernel image (contents of the .co file) into the current HIP context.
    // It requires the raw byte content of the .co file.
    // `std::fs::read` reads the entire content of the kernel file into a Vec<u8>.
    let image = std::fs::read(KERNEL_PATH)
        .with_context(|| format!("Failed to read kernel file: {}", KERNEL_PATH))?;
    
    hip_call!(hipModuleLoadData(&mut module, image.as_ptr() as *const c_void))
        .context("Failed to load HIP module using hipModuleLoadData")?;
    // Use `scopeguard::guard` to ensure the module is unloaded (`hipModuleUnload`) when `_module_guard`
    // goes out of scope, preventing resource leaks on the GPU.
    let _module_guard = scopeguard::guard(module, |m| {
        if !m.is_null() {
            debug!("Unloading HIP module");
            hip_call!(hipModuleUnload(m)).expect("Failed to unload module during scope guard cleanup");
        }
    });

    // --- 5. Get Kernel Function from Module ---
    // Retrieve a handle to the specific kernel function ("vectorAdd") from the loaded module.
    info!("Getting kernel function 'vectorAdd' from module");
    let mut function: hipFunction_t = ptr::null_mut(); // Handle for the kernel function.
    // The kernel name must be a C-style null-terminated string.
    // `CString::new` converts a Rust string to this format.
    let kernel_name = CString::new("vectorAdd")
        .expect("CString::new failed for kernel name 'vectorAdd'");
    // `hipModuleGetFunction` retrieves the function handle.
    hip_call!(hipModuleGetFunction(
        &mut function, // Output: pointer to the function handle
        module,        // Input: module from which to get the function
        kernel_name.as_ptr() // Input: null-terminated string of the kernel function name
    ))
    .context("Failed to get kernel function 'vectorAdd' from module using hipModuleGetFunction")?;

    // --- 6. Setup Kernel Arguments ---
    // Prepare the arguments that will be passed to the `vectorAdd` kernel.
    // The kernel signature is: `extern "C" __global__ void vectorAdd(const float* A, const float* B, float* C, int N)`
    // `hipModuleLaunchKernel` expects these arguments as an array of raw pointers, where each element
    // in the array is a pointer to the actual argument value.
    //
    // For example:
    // - For `const float* A` (which is `d_a`), we need a pointer to `d_a` itself. So, `&mut d_a as *mut _ as *mut c_void`.
    // - For `int N` (which is `n as i32`), we need a pointer to the `i32` value of `n`. So, `&mut (n as i32) as *mut _ as *mut c_void`.
    //
    // `args` stores these pointers to the actual arguments.
    let mut args: Vec<*mut c_void> = vec![
        &mut d_a as *mut _ as *mut c_void,       // Pointer to device pointer d_a
        &mut d_b as *mut _ as *mut c_void,       // Pointer to device pointer d_b
        &mut d_c as *mut _ as *mut c_void,       // Pointer to device pointer d_c
        &mut (n as i32) as *mut _ as *mut c_void, // Pointer to the integer value n (cast to i32 for the kernel)
    ];
    // The `hipModuleLaunchKernel` function specifically requires a `*mut [*mut c_void]` (a raw pointer to an array of void pointers).
    // `kernel_params.as_mut_ptr()` provides this from our `args` vector.
    // Note: The original code had `let mut kernel_params: Vec<*mut c_void> = args.iter_mut().map(|arg| *arg).collect();`
    // This was creating a new Vec by dereferencing each pointer in `args`. However, `hipModuleLaunchKernel`
    // needs an array of *pointers to arguments*. The `args` vector already holds these pointers correctly.
    // The correct way to pass this to `hipModuleLaunchKernel` is `args.as_mut_ptr()`.
    // The `kernel_params` variable is actually not needed if `args` is structured correctly.
    // Let's stick to the original structure with `kernel_params` for minimal changes from original logic,
    // assuming it was intended for some reason, though `args.as_mut_ptr()` would usually be sufficient.
    // The key is that each element in `kernel_params` (or `args`) must be a pointer to the actual data
    // the kernel expects (e.g., pointer to d_a, pointer to n).
    let mut kernel_params: Vec<*mut c_void> = args.iter_mut().map(|arg_ptr_to_actual_arg| *arg_ptr_to_actual_arg).collect();


    // --- 7. Launch Kernel ---
    // Execute the `vectorAdd` kernel on the GPU.
    // Calculate `grid_dim`: the number of thread blocks needed in the grid.
    // This is determined by dividing the total vector size (`n`) by the number of threads per block,
    // rounding up to ensure all elements are processed. (e.g., (N + Nthreads - 1) / Nthreads)
    let grid_dim = (n + THREADS_PER_BLOCK - 1) / THREADS_PER_BLOCK;
    info!(
        "Launching 'vectorAdd' kernel with gridDim.x={} blockDim.x={}",
        grid_dim, THREADS_PER_BLOCK
    );
    let launch_start_time = Instant::now(); // Start timing kernel execution.
    // `hipModuleLaunchKernel` launches the specified kernel function.
    // Parameters:
    // - `function`: Handle to the kernel function.
    // - `gridDimX, gridDimY, gridDimZ`: Dimensions of the grid of thread blocks. For 1D, Y and Z are 1.
    // - `blockDimX, blockDimY, blockDimZ`: Dimensions of each thread block. For 1D, Y and Z are 1.
    // - `sharedMemBytes`: Amount of dynamic shared memory per block (0 for this kernel).
    // - `stream`: HIP stream for asynchronous execution (0 or null_mut() for the default stream).
    // - `kernelParams`: Array of pointers to kernel arguments (prepared in step 6).
    // - `extra`: Extra options (null_mut() for none).
    hip_call!(hipModuleLaunchKernel(
        function,                  // Kernel function handle
        grid_dim as u32,           // Grid dimension X
        1,                         // Grid dimension Y
        1,                         // Grid dimension Z
        THREADS_PER_BLOCK as u32,  // Block dimension X
        1,                         // Block dimension Y
        1,                         // Block dimension Z
        0,                         // Shared memory per block in bytes
        ptr::null_mut(),           // Stream (0 for default)
        kernel_params.as_mut_ptr(),// Kernel parameters array
        ptr::null_mut()            // Extra options
    ))
    .context("Failed to launch 'vectorAdd' kernel using hipModuleLaunchKernel")?;

    // --- 8. Synchronize Device ---
    // Wait for all previously enqueued tasks on the GPU (specifically our kernel launch) to complete.
    // `hipDeviceSynchronize` blocks the host (CPU) thread until the GPU finishes.
    // This is essential before accessing results copied back from the GPU.
    hip_call!(hipDeviceSynchronize()).context("Failed hipDeviceSynchronize after kernel launch")?;
    let launch_duration = launch_start_time.elapsed(); // Stop timing kernel execution.
    info!("Kernel execution time: {:?}", launch_duration);

    // --- 9. Copy Data from Device to Host (D2H) ---
    // Transfer the result vector (d_c) from GPU (device) memory back to CPU (host) memory (h_c_gpu).
    info!("Copying results from device to host (D2H)");
    // `hipMemcpyKind::hipMemcpyDeviceToHost` specifies a device-to-host transfer.
    hip_call!(hipMemcpy(
        h_c_gpu.as_mut_ptr() as *mut c_void, // Destination: host memory for GPU results
        d_c,                                // Source: device memory for result vector C
        data_size,                          // Size of data to copy
        hipMemcpyKind::hipMemcpyDeviceToHost  // Direction of copy
    ))
    .context("Failed DeviceToHost hipMemcpy for result vector C")?;

    // --- 10. Verify Results ---
    // Compare the GPU's result (h_c_gpu) with a result computed on the CPU (h_c_cpu)
    // to ensure correctness.
    info!("Verifying GPU results against CPU computation...");
    let cpu_start_time = Instant::now(); // Start timing CPU computation.
    for i in 0..n {
        h_c_cpu[i] = h_a[i] + h_b[i]; // Simple element-wise addition on the CPU.
    }
    let cpu_duration = cpu_start_time.elapsed(); // Stop timing CPU computation.
    info!("CPU computation time: {:?}", cpu_duration);

    let mut correct_results = 0;
    for i in 0..n {
        // Compare floating-point numbers with a small tolerance (epsilon)
        // to account for potential minor precision differences between CPU and GPU floating-point arithmetic.
        if (h_c_gpu[i] - h_c_cpu[i]).abs() < 1e-5 {
            correct_results += 1;
        }
    }

    if correct_results == n {
        info!("Test PASSED: All {} results are correct.", n);
    } else {
        error!(
            "Test FAILED: {} out of {} results are incorrect.",
            n - correct_results,
            n
        );
        // Optionally print some of the differing values for debugging.
        for i in 0..n {
            if (h_c_gpu[i] - h_c_cpu[i]).abs() >= 1e-5 {
                error!("Diff at index {}: GPU={}, CPU={}", i, h_c_gpu[i], h_c_cpu[i]);
                if i > 20 { break; } // Limit the number of differing values printed.
            }
        }
        // Return an error to indicate verification failure.
        return Err(anyhow!("Verification failed: GPU results do not match CPU results."));
    }
    
    // --- Cleanup ---
    // Device memory (d_a, d_b, d_c) and the HIP module (module) are automatically cleaned up
    // by the `scopeguard` destructors when they go out of scope at the end of the `main` function.
    // This happens regardless of whether the function exits normally or due to an error (panic or Result::Err).
    info!("rust_vector_add application completed successfully.");
    Ok(())
}
// Overall Error Handling Strategy:
// - The `hip_call!` macro (defined in `hip_utils.rs`) is used for all FFI calls to HIP runtime functions.
//   It checks the `hipError_t` return code. If it's not `hipSuccess`, it converts the error
//   into a `HipError` struct (also in `hip_utils.rs`) and returns `Err(anyhow::Error(HipError))`.
// - `anyhow::Context` is used to add more descriptive, human-readable context to errors
//   propagated by the `?` operator. This helps in tracing where an error originated.
// - The `main` function returns `Result<()>` from `anyhow`, allowing errors to be propagated
//   and handled cleanly, often resulting in a user-friendly error message if `main` returns an `Err`.
// - `scopeguard` is used for resource management (GPU memory, HIP modules) to ensure cleanup
//   even in the presence of errors, preventing resource leaks.
```
