// This file includes the Rust bindings generated by `bindgen` in `build.rs`.

// Suppress warnings for C-style names generated by bindgen.
#![allow(non_upper_case_globals)] // For constants like hipSuccess.
#![allow(non_camel_case_types)]  // For types like hipDeviceProp_t.
#![allow(non_snake_case)]      // For function names and struct fields.
#![allow(dead_code)]           // To suppress warnings for unused bindings if any part is not used by the app.

// Include the generated bindings.
// The `concat!` macro and `env!("OUT_DIR")` are standard ways to locate the generated file.
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

// Additional sanity checks or type re-definitions can be done here if needed,
// but ideally, bindgen and build.rs configure everything correctly.

// For example, if `hipSuccess` was not correctly picked up as a const by `allowlist_var`
// (e.g., if it's a `#define hipSuccess 0` and bindgen didn't convert it to `pub const hipSuccess: hipError_t = 0;`),
// and if `hipError_t` is a known type (e.g. i32 after rustification or as raw c_int),
// you might define it here:
//
// ```rust
// pub const hipSuccessValue: hipError_t = 0; // Use this if `hipSuccess` from bindings.rs is problematic.
// ```
// However, `allowlist_var("hipSuccess")` in `build.rs` should handle this correctly for defines
// that evaluate to integer constants. The `.rustified_enum("hipError_t")` might also affect how
// hipSuccess (if it were an enum variant) is represented.
// For now, we assume `bindings.rs` provides a usable `hipError_t` type and a `hipSuccess` constant.
// The application code in `safe_hip_wrappers.rs` will use `ffi::hipSuccess`.
